test:
    description: "This is a smoke test that checks that guest images can load and run programs"

    targets:
        - "$(GUEST_FS)/program files/microsoft office/office14/winword.exe"
        - "$(GUEST_FS)/program files/microsoft office/office15/winword.exe"
        - "$(GUEST_FS)/program files/microsoft office/root/office16/winword.exe"
        - "$(GUEST_FS)/program files (x86)/microsoft office/office14/winword.exe"
        - "$(GUEST_FS)/program files (x86)/microsoft office/office15/winword.exe"
        - "$(GUEST_FS)/program files (x86)/microsoft office/root/office16/winword.exe"

    target_arguments:
        - $(TEST_ROOT)/test.docm

    target-images:
        - office
