test:
    description: "Checks that basic symbolic execution works by forking two paths"

    target_arguments:
        - "@@"

    targets:
        - windows64-basic1-twopaths.exe
        - windows32-basic1-twopaths.exe
        - linux32-basic1-twopaths
        - linux64-basic1-twopaths

    # Avoid forced concretizations on these images
    blacklisted-images:
        - windows-8.1ent-x86_64
        - windows-10ent1703-x86_64

    build-options:
        post-project-generation-script: fix-config.sh
